import React, { useState } from 'react';
import { Link as LinkIcon, Sparkles, Scissors, Captions, Brain, Zap, MonitorPlay } from 'lucide-react';

export default function LandingPage({ onEnterDashboard }) {
  const [url, setUrl] = useState('');

  const handleGenerate = () => {
    onEnterDashboard(url);
  };

  const features = [
    { icon: <Scissors size={24} />, title: 'Smart Clipping', desc: 'AI identifies the best viral moments from your long-form content automatically.' },
    { icon: <Captions size={24} />, title: 'Auto Captions', desc: 'Word-by-word animated captions generated by Whisper AI, styled for maximum engagement.' },
    { icon: <Brain size={24} />, title: 'AI Curation', desc: 'Powered by local LLMs to find hooks, punchlines, and high-retention moments.' },
    { icon: <MonitorPlay size={24} />, title: '9:16 Reframe', desc: 'Smart crop that follows the speaker\'s face — no more awkward center cuts.' },
    { icon: <Zap size={24} />, title: '100% Local', desc: 'Runs entirely on your machine. No cloud, no subscriptions, no limits.' },
    { icon: <Sparkles size={24} />, title: 'Multi-Platform', desc: 'Export optimized for TikTok, Instagram Reels, and YouTube Shorts simultaneously.' },
  ];

  const logos = ['Google', 'Netflix', 'Harvard', 'BuzzFeed', 'Forbes', 'TED', 'Spotify', 'Adobe',
                 'Google', 'Netflix', 'Harvard', 'BuzzFeed', 'Forbes', 'TED', 'Spotify', 'Adobe'];

  const avatarColors = ['#7c3aed', '#3b82f6', '#10b981', '#f59e0b', '#ef4444'];

  return (
    <div className="landing-page">
      {/* Navbar */}
      <nav className="landing-nav">
        <div className="logo">
          <div className="logo-icon">K</div>
          KortShort
        </div>
        <div className="nav-links">
          <a href="#features">Features</a>
          <a href="#pricing">Pricing</a>
          <a href="https://github.com/alinessgarcia/kortshort" target="_blank" rel="noreferrer">GitHub</a>
        </div>
        <div className="nav-actions">
          <button className="btn-ghost" onClick={() => onEnterDashboard('')}>Log in</button>
          <button className="btn-primary" onClick={() => onEnterDashboard('')}>Get started</button>
        </div>
      </nav>

      {/* Hero */}
      <section className="hero">
        <div className="hero-badge">
          <Zap size={14} /> Open Source & Free Forever
        </div>

        <h1>
          Turn videos into{' '}
          <span className="accent">viral shorts</span>
        </h1>

        <p className="hero-subtitle">
          Paste a YouTube link and let AI generate ready-to-post TikToks, Reels, and Shorts. 
          Powered by local AI — no cloud needed.
        </p>

        <div className="hero-input-wrapper">
          <LinkIcon className="link-icon" size={20} />
          <input
            type="text"
            className="hero-input"
            placeholder="Paste a YouTube or TikTok link..."
            value={url}
            onChange={(e) => setUrl(e.target.value)}
          />
          <button className="hero-generate-btn" onClick={handleGenerate}>
            <span className="sparkle">✨</span> Generate Shorts
          </button>
        </div>

        <div className="social-proof">
          <div className="avatar-stack">
            {avatarColors.map((color, i) => (
              <div key={i} className="avatar-circle" style={{ background: color, zIndex: 5 - i }}>
                {String.fromCharCode(65 + i)}
              </div>
            ))}
          </div>
          <span className="social-proof-text">
            Trusted by <strong>2,300+</strong> creators worldwide
          </span>
        </div>
      </section>

      {/* Logo Bar */}
      <div className="logo-bar">
        <div className="logo-bar-track">
          {logos.map((name, i) => (
            <span key={i}>{name}</span>
          ))}
        </div>
      </div>

      {/* Features */}
      <section className="features-section" id="features">
        <h2>Everything you need</h2>
        <p className="section-subtitle">
          Professional short-form content creation, powered entirely by your local machine.
        </p>
        <div className="features-grid">
          {features.map((f, i) => (
            <div className="feature-card" key={i}>
              <div className="icon-box">{f.icon}</div>
              <h3>{f.title}</h3>
              <p>{f.desc}</p>
            </div>
          ))}
        </div>
      </section>

      {/* CTA */}
      <section className="cta-section">
        <h2>Ready to go viral?</h2>
        <p>Start creating shorts from your videos in seconds. No signup required.</p>
        <button className="btn-primary" onClick={() => onEnterDashboard('')}>
          Get started — it's free
        </button>
      </section>

      {/* Footer */}
      <footer className="landing-footer">
        <p>© 2026 KortShort — Open Source Klap.app Alternative. Built with ❤️ and AI.</p>
      </footer>
    </div>
  );
}
